/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import desplazable.Desface;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author pc
 */
public class FrmChessGame extends javax.swing.JFrame {

    //se inicializa la variable de la clase de desplazamiento
    Desface desplazamiento = new Desface();

    PnlRegistroDeJugadores pnlRegistroDeJugadores;
    PnlTablero pnlTablero;

    // PnlTablero pnlTablero;

    /**
     * Creates new form FrmChessGame
     */
    public FrmChessGame() {
        initComponents();
        //para que la ventana aparezca en el centro y no en la esquina
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlMenuIzquierdo = new javax.swing.JPanel();
        pnlFondoAzul = new javax.swing.JPanel();
        pnlJugar = new javax.swing.JPanel();
        lblIconoJugar = new javax.swing.JLabel();
        lblJugar = new javax.swing.JLabel();
        pnlPuntuaciones = new javax.swing.JPanel();
        lblIconoPuntuaciones = new javax.swing.JLabel();
        lblPuntuaciones = new javax.swing.JLabel();
        pnlCreditos = new javax.swing.JPanel();
        lblICreditos = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        pnlMenuDerecho = new javax.swing.JPanel();
        lblImagenAjedrezProvicional = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenuIzquierdo.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenuIzquierdo.setLayout(null);

        pnlFondoAzul.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlFondoAzulLayout = new javax.swing.GroupLayout(pnlFondoAzul);
        pnlFondoAzul.setLayout(pnlFondoAzulLayout);
        pnlFondoAzulLayout.setHorizontalGroup(
            pnlFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        pnlFondoAzulLayout.setVerticalGroup(
            pnlFondoAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        pnlMenuIzquierdo.add(pnlFondoAzul);
        pnlFondoAzul.setBounds(0, 60, 650, 80);

        pnlJugar.setBackground(new java.awt.Color(0, 41, 133));
        pnlJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlJugar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlJugarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlJugarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlJugarMouseExited(evt);
            }
        });

        lblIconoJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Jugar.png"))); // NOI18N

        lblJugar.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblJugar.setForeground(new java.awt.Color(255, 255, 255));
        lblJugar.setText("JUGAR");

        javax.swing.GroupLayout pnlJugarLayout = new javax.swing.GroupLayout(pnlJugar);
        pnlJugar.setLayout(pnlJugarLayout);
        pnlJugarLayout.setHorizontalGroup(
            pnlJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(lblIconoJugar)
                .addGap(23, 23, 23))
        );
        pnlJugarLayout.setVerticalGroup(
            pnlJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJugarLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlJugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIconoJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJugar))
                .addGap(20, 20, 20))
        );

        pnlMenuIzquierdo.add(pnlJugar);
        pnlJugar.setBounds(-270, 240, 360, 80);

        pnlPuntuaciones.setBackground(new java.awt.Color(0, 41, 133));
        pnlPuntuaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPuntuaciones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlPuntuaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPuntuacionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPuntuacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPuntuacionesMouseExited(evt);
            }
        });

        lblIconoPuntuaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Puntuación.png"))); // NOI18N

        lblPuntuaciones.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblPuntuaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntuaciones.setText("PUNTUACIONES");

        javax.swing.GroupLayout pnlPuntuacionesLayout = new javax.swing.GroupLayout(pnlPuntuaciones);
        pnlPuntuaciones.setLayout(pnlPuntuacionesLayout);
        pnlPuntuacionesLayout.setHorizontalGroup(
            pnlPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPuntuacionesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPuntuaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblIconoPuntuaciones)
                .addGap(23, 23, 23))
        );
        pnlPuntuacionesLayout.setVerticalGroup(
            pnlPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPuntuacionesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlPuntuacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoPuntuaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuntuaciones))
                .addGap(20, 20, 20))
        );

        pnlMenuIzquierdo.add(pnlPuntuaciones);
        pnlPuntuaciones.setBounds(-270, 350, 360, 80);

        pnlCreditos.setBackground(new java.awt.Color(0, 41, 133));
        pnlCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCreditos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pnlCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlCreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCreditosMouseExited(evt);
            }
        });

        lblICreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Créditos.png"))); // NOI18N

        lblCreditos.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        lblCreditos.setForeground(new java.awt.Color(255, 255, 255));
        lblCreditos.setText("CRÉDITOS");

        javax.swing.GroupLayout pnlCreditosLayout = new javax.swing.GroupLayout(pnlCreditos);
        pnlCreditos.setLayout(pnlCreditosLayout);
        pnlCreditosLayout.setHorizontalGroup(
            pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreditosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(lblICreditos)
                .addGap(23, 23, 23))
        );
        pnlCreditosLayout.setVerticalGroup(
            pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCreditosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblICreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreditos))
                .addGap(20, 20, 20))
        );

        pnlMenuIzquierdo.add(pnlCreditos);
        pnlCreditos.setBounds(-270, 460, 360, 80);

        pnlFondo.add(pnlMenuIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 600));

        pnlMenuDerecho.setBackground(new java.awt.Color(255, 255, 255));

        lblImagenAjedrezProvicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Chess.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlMenuDerechoLayout = new javax.swing.GroupLayout(pnlMenuDerecho);
        pnlMenuDerecho.setLayout(pnlMenuDerechoLayout);
        pnlMenuDerechoLayout.setHorizontalGroup(
            pnlMenuDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenAjedrezProvicional, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlMenuDerechoLayout.setVerticalGroup(
            pnlMenuDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImagenAjedrezProvicional, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlFondo.add(pnlMenuDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 350, 600));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlJugarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlJugarMouseEntered

        if (pnlJugar.getX() >= -270 && pnlJugar.getX() <= 0) {
// libreria importada de desplazamiento
            //( objeto a mover | desde donde comienza  | donde termina | pasos en ir de a hacia b | tiempo)
            desplazamiento.desplazarDerecha(pnlJugar, -270, 0, 10, 15);
        }

    }//GEN-LAST:event_pnlJugarMouseEntered

    private void pnlJugarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlJugarMouseExited

        // lo mismo pero al revés el inicio y final
        desplazamiento.desplazarIzquierda(pnlJugar, 0, -270, 10, 15);
    }//GEN-LAST:event_pnlJugarMouseExited

    private void pnlPuntuacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPuntuacionesMouseEntered
        // TODO add your handling code here:
        desplazamiento.desplazarDerecha(pnlPuntuaciones, -270, 0, 10, 15);
    }//GEN-LAST:event_pnlPuntuacionesMouseEntered

    private void pnlPuntuacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPuntuacionesMouseExited
        // TODO add your handling code here:
        desplazamiento.desplazarIzquierda(pnlPuntuaciones, 0, -270, 10, 15);
    }//GEN-LAST:event_pnlPuntuacionesMouseExited

    private void pnlCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreditosMouseEntered
        // TODO add your handling code here:
        desplazamiento.desplazarDerecha(pnlCreditos, -270, 0, 10, 15);
    }//GEN-LAST:event_pnlCreditosMouseEntered

    private void pnlCreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCreditosMouseExited
        // TODO add your handling code here:
        desplazamiento.desplazarIzquierda(pnlCreditos, 0, -270, 10, 15);
    }//GEN-LAST:event_pnlCreditosMouseExited

    private void pnlJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlJugarMouseClicked
        // TODO add your handling code here:
        pnlRegistroDeJugadores = new PnlRegistroDeJugadores();
        agregarPanelDerecho(pnlRegistroDeJugadores);

        pnlTablero = new PnlTablero();
        agregarPanelIzquierdo(pnlTablero);


    }//GEN-LAST:event_pnlJugarMouseClicked

    private void pnlPuntuacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPuntuacionesMouseClicked
        // TODO add your handling code here:
        pnlPuntuaciones = new PnlPuntuaciones();
        agregarPanelDerecho(pnlPuntuaciones);
    }//GEN-LAST:event_pnlPuntuacionesMouseClicked

    private void agregarPanelDerecho(JPanel pnl) {
        //ajustamos el tamaño
        pnl.setSize(350, 600);
        //colocamos, la esquina superior izquierda posee coordenadas (0,0)
        pnl.setLocation(0, 0);
        //remueve lo del panel inicio
        pnlMenuDerecho.removeAll();
        //en el panel inicio agregue el panel clientes con una ubicación
        pnlMenuDerecho.add(pnl, BorderLayout.CENTER);
        //elimina toda la jerarquia y la construye nuevamente
        pnlMenuDerecho.revalidate();
        pnlMenuDerecho.repaint();
    }

    private void agregarPanelIzquierdo(JPanel pnl) {
        //ajustamos el tamaño
        pnl.setSize(650, 600);
        //colocamos, la esquina superior izquierda posee coordenadas (0,0)
        pnl.setLocation(0, 0);
        //remueve lo del panel inicio
        pnlMenuIzquierdo.removeAll();
        //en el panel inicio agregue el panel clientes con una ubicación
        pnlMenuIzquierdo.add(pnl, BorderLayout.CENTER);
        //elimina toda la jerarquia y la construye nuevamente
        pnlMenuIzquierdo.revalidate();
        pnlMenuIzquierdo.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmChessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmChessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmChessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmChessGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmChessGame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblICreditos;
    private javax.swing.JLabel lblIconoJugar;
    private javax.swing.JLabel lblIconoPuntuaciones;
    private javax.swing.JLabel lblImagenAjedrezProvicional;
    private javax.swing.JLabel lblJugar;
    private javax.swing.JLabel lblPuntuaciones;
    private javax.swing.JPanel pnlCreditos;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlFondoAzul;
    private javax.swing.JPanel pnlJugar;
    private javax.swing.JPanel pnlMenuDerecho;
    private javax.swing.JPanel pnlMenuIzquierdo;
    private javax.swing.JPanel pnlPuntuaciones;
    // End of variables declaration//GEN-END:variables
}
