/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author pc
 */
public class PnlTablero extends javax.swing.JPanel {

    /**
     * Creates new form PnlTablero
     */
    public PnlTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoTablero = new javax.swing.JPanel();
        pnlA8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlA9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnlA10 = new javax.swing.JPanel();
        pnlA11 = new javax.swing.JPanel();
        pnlA12 = new javax.swing.JPanel();
        pnlA13 = new javax.swing.JPanel();
        pnlA14 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        pnlA15 = new javax.swing.JPanel();
        pnlA16 = new javax.swing.JPanel();
        pnlA17 = new javax.swing.JPanel();
        pnlA18 = new javax.swing.JPanel();
        pnlA19 = new javax.swing.JPanel();
        pnlA20 = new javax.swing.JPanel();
        pnlA21 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        pnlA22 = new javax.swing.JPanel();
        pnlA23 = new javax.swing.JPanel();
        pnlA24 = new javax.swing.JPanel();
        pnlA25 = new javax.swing.JPanel();
        pnlA26 = new javax.swing.JPanel();
        pnlA27 = new javax.swing.JPanel();
        pnlA28 = new javax.swing.JPanel();
        pnlA29 = new javax.swing.JPanel();
        pnlA30 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        pnlA31 = new javax.swing.JPanel();
        pnlA32 = new javax.swing.JPanel();
        pnlA33 = new javax.swing.JPanel();
        pnlA34 = new javax.swing.JPanel();
        pnlA35 = new javax.swing.JPanel();
        pnlA36 = new javax.swing.JPanel();
        pnlA37 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        pnlA38 = new javax.swing.JPanel();
        pnlA39 = new javax.swing.JPanel();
        pnlA40 = new javax.swing.JPanel();
        pnlBordeIzquierdo = new javax.swing.JPanel();
        pnlBordeSuperior = new javax.swing.JPanel();
        pnlBordeDerecho = new javax.swing.JPanel();
        pnlBordeInferior = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlFondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlA8.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoTablero.add(pnlA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 70, 70));

        jPanel2.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 70, 70));

        pnlA9.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoTablero.add(pnlA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 70));

        jPanel3.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 70, 70));

        jPanel4.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 70, 70));

        jPanel5.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 70));

        pnlA10.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA10Layout = new javax.swing.GroupLayout(pnlA10);
        pnlA10.setLayout(pnlA10Layout);
        pnlA10Layout.setHorizontalGroup(
            pnlA10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA10Layout.setVerticalGroup(
            pnlA10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, 70));

        pnlA11.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA11Layout = new javax.swing.GroupLayout(pnlA11);
        pnlA11.setLayout(pnlA11Layout);
        pnlA11Layout.setHorizontalGroup(
            pnlA11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA11Layout.setVerticalGroup(
            pnlA11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 70, 70));

        pnlA12.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA12Layout = new javax.swing.GroupLayout(pnlA12);
        pnlA12.setLayout(pnlA12Layout);
        pnlA12Layout.setHorizontalGroup(
            pnlA12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA12Layout.setVerticalGroup(
            pnlA12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 70, 70));

        pnlA13.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA13Layout = new javax.swing.GroupLayout(pnlA13);
        pnlA13.setLayout(pnlA13Layout);
        pnlA13Layout.setHorizontalGroup(
            pnlA13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA13Layout.setVerticalGroup(
            pnlA13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 70));

        pnlA14.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA14Layout = new javax.swing.GroupLayout(pnlA14);
        pnlA14.setLayout(pnlA14Layout);
        pnlA14Layout.setHorizontalGroup(
            pnlA14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA14Layout.setVerticalGroup(
            pnlA14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 70));

        jPanel6.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, 70));

        jPanel7.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 70));

        jPanel8.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 70));

        jPanel9.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 70, 70));

        jPanel10.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 70));

        jPanel11.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 70));

        pnlA15.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA15Layout = new javax.swing.GroupLayout(pnlA15);
        pnlA15.setLayout(pnlA15Layout);
        pnlA15Layout.setHorizontalGroup(
            pnlA15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA15Layout.setVerticalGroup(
            pnlA15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, 70));

        pnlA16.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA16Layout = new javax.swing.GroupLayout(pnlA16);
        pnlA16.setLayout(pnlA16Layout);
        pnlA16Layout.setHorizontalGroup(
            pnlA16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA16Layout.setVerticalGroup(
            pnlA16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 70));

        pnlA17.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA17Layout = new javax.swing.GroupLayout(pnlA17);
        pnlA17.setLayout(pnlA17Layout);
        pnlA17Layout.setHorizontalGroup(
            pnlA17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA17Layout.setVerticalGroup(
            pnlA17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        pnlA18.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA18Layout = new javax.swing.GroupLayout(pnlA18);
        pnlA18.setLayout(pnlA18Layout);
        pnlA18Layout.setHorizontalGroup(
            pnlA18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA18Layout.setVerticalGroup(
            pnlA18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 70));

        pnlA19.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA19Layout = new javax.swing.GroupLayout(pnlA19);
        pnlA19.setLayout(pnlA19Layout);
        pnlA19Layout.setHorizontalGroup(
            pnlA19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA19Layout.setVerticalGroup(
            pnlA19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, 70));

        pnlA20.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA20Layout = new javax.swing.GroupLayout(pnlA20);
        pnlA20.setLayout(pnlA20Layout);
        pnlA20Layout.setHorizontalGroup(
            pnlA20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA20Layout.setVerticalGroup(
            pnlA20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 70, 70));

        pnlA21.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA21Layout = new javax.swing.GroupLayout(pnlA21);
        pnlA21.setLayout(pnlA21Layout);
        pnlA21Layout.setHorizontalGroup(
            pnlA21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA21Layout.setVerticalGroup(
            pnlA21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, 70));

        jPanel12.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 70, 70));

        jPanel13.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, 70));

        jPanel14.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 70));

        jPanel15.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 70));

        jPanel16.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 70));

        jPanel17.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 70));

        jPanel18.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 70));

        jPanel19.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 70, 70));

        pnlA22.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA22Layout = new javax.swing.GroupLayout(pnlA22);
        pnlA22.setLayout(pnlA22Layout);
        pnlA22Layout.setHorizontalGroup(
            pnlA22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA22Layout.setVerticalGroup(
            pnlA22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, 70));

        pnlA23.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA23Layout = new javax.swing.GroupLayout(pnlA23);
        pnlA23.setLayout(pnlA23Layout);
        pnlA23Layout.setHorizontalGroup(
            pnlA23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA23Layout.setVerticalGroup(
            pnlA23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 70));

        pnlA24.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA24Layout = new javax.swing.GroupLayout(pnlA24);
        pnlA24.setLayout(pnlA24Layout);
        pnlA24Layout.setHorizontalGroup(
            pnlA24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA24Layout.setVerticalGroup(
            pnlA24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 70));

        pnlA25.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA25Layout = new javax.swing.GroupLayout(pnlA25);
        pnlA25.setLayout(pnlA25Layout);
        pnlA25Layout.setHorizontalGroup(
            pnlA25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA25Layout.setVerticalGroup(
            pnlA25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 70));

        pnlA26.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA26Layout = new javax.swing.GroupLayout(pnlA26);
        pnlA26.setLayout(pnlA26Layout);
        pnlA26Layout.setHorizontalGroup(
            pnlA26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA26Layout.setVerticalGroup(
            pnlA26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, 70));

        pnlA27.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA27Layout = new javax.swing.GroupLayout(pnlA27);
        pnlA27.setLayout(pnlA27Layout);
        pnlA27Layout.setHorizontalGroup(
            pnlA27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA27Layout.setVerticalGroup(
            pnlA27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, 70));

        pnlA28.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA28Layout = new javax.swing.GroupLayout(pnlA28);
        pnlA28.setLayout(pnlA28Layout);
        pnlA28Layout.setHorizontalGroup(
            pnlA28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA28Layout.setVerticalGroup(
            pnlA28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        pnlA29.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA29Layout = new javax.swing.GroupLayout(pnlA29);
        pnlA29.setLayout(pnlA29Layout);
        pnlA29Layout.setHorizontalGroup(
            pnlA29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA29Layout.setVerticalGroup(
            pnlA29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, 70));

        pnlA30.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA30Layout = new javax.swing.GroupLayout(pnlA30);
        pnlA30.setLayout(pnlA30Layout);
        pnlA30Layout.setHorizontalGroup(
            pnlA30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA30Layout.setVerticalGroup(
            pnlA30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 70, 70));

        jPanel20.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 70));

        jPanel21.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 70));

        jPanel22.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 70));

        jPanel23.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 70));

        jPanel24.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 70));

        jPanel25.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 70));

        jPanel26.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, 70));

        jPanel27.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 70));

        pnlA31.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA31Layout = new javax.swing.GroupLayout(pnlA31);
        pnlA31.setLayout(pnlA31Layout);
        pnlA31Layout.setHorizontalGroup(
            pnlA31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA31Layout.setVerticalGroup(
            pnlA31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 70));

        pnlA32.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA32Layout = new javax.swing.GroupLayout(pnlA32);
        pnlA32.setLayout(pnlA32Layout);
        pnlA32Layout.setHorizontalGroup(
            pnlA32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA32Layout.setVerticalGroup(
            pnlA32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 70));

        pnlA33.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA33Layout = new javax.swing.GroupLayout(pnlA33);
        pnlA33.setLayout(pnlA33Layout);
        pnlA33Layout.setHorizontalGroup(
            pnlA33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA33Layout.setVerticalGroup(
            pnlA33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 70));

        pnlA34.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA34Layout = new javax.swing.GroupLayout(pnlA34);
        pnlA34.setLayout(pnlA34Layout);
        pnlA34Layout.setHorizontalGroup(
            pnlA34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA34Layout.setVerticalGroup(
            pnlA34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA34, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, 70));

        pnlA35.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA35Layout = new javax.swing.GroupLayout(pnlA35);
        pnlA35.setLayout(pnlA35Layout);
        pnlA35Layout.setHorizontalGroup(
            pnlA35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA35Layout.setVerticalGroup(
            pnlA35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, 70));

        pnlA36.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA36Layout = new javax.swing.GroupLayout(pnlA36);
        pnlA36.setLayout(pnlA36Layout);
        pnlA36Layout.setHorizontalGroup(
            pnlA36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA36Layout.setVerticalGroup(
            pnlA36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        pnlA37.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA37Layout = new javax.swing.GroupLayout(pnlA37);
        pnlA37.setLayout(pnlA37Layout);
        pnlA37Layout.setHorizontalGroup(
            pnlA37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA37Layout.setVerticalGroup(
            pnlA37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        jPanel28.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 70));

        jPanel29.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 70));

        jPanel30.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 70));

        jPanel31.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 70));

        jPanel32.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 70));

        jPanel33.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));

        pnlA38.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA38Layout = new javax.swing.GroupLayout(pnlA38);
        pnlA38.setLayout(pnlA38Layout);
        pnlA38Layout.setHorizontalGroup(
            pnlA38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA38Layout.setVerticalGroup(
            pnlA38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 70));

        pnlA39.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA39Layout = new javax.swing.GroupLayout(pnlA39);
        pnlA39.setLayout(pnlA39Layout);
        pnlA39Layout.setHorizontalGroup(
            pnlA39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA39Layout.setVerticalGroup(
            pnlA39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA39, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 70));

        pnlA40.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA40Layout = new javax.swing.GroupLayout(pnlA40);
        pnlA40.setLayout(pnlA40Layout);
        pnlA40Layout.setHorizontalGroup(
            pnlA40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA40Layout.setVerticalGroup(
            pnlA40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 70));

        pnlBordeIzquierdo.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeIzquierdoLayout = new javax.swing.GroupLayout(pnlBordeIzquierdo);
        pnlBordeIzquierdo.setLayout(pnlBordeIzquierdoLayout);
        pnlBordeIzquierdoLayout.setHorizontalGroup(
            pnlBordeIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlBordeIzquierdoLayout.setVerticalGroup(
            pnlBordeIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlBordeSuperior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeSuperiorLayout = new javax.swing.GroupLayout(pnlBordeSuperior);
        pnlBordeSuperior.setLayout(pnlBordeSuperiorLayout);
        pnlBordeSuperiorLayout.setHorizontalGroup(
            pnlBordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlBordeSuperiorLayout.setVerticalGroup(
            pnlBordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBordeDerecho.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeDerechoLayout = new javax.swing.GroupLayout(pnlBordeDerecho);
        pnlBordeDerecho.setLayout(pnlBordeDerechoLayout);
        pnlBordeDerechoLayout.setHorizontalGroup(
            pnlBordeDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlBordeDerechoLayout.setVerticalGroup(
            pnlBordeDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlBordeInferior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeInferiorLayout = new javax.swing.GroupLayout(pnlBordeInferior);
        pnlBordeInferior.setLayout(pnlBordeInferiorLayout);
        pnlBordeInferiorLayout.setHorizontalGroup(
            pnlBordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlBordeInferiorLayout.setVerticalGroup(
            pnlBordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlBordeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBordeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBordeDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBordeIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBordeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(pnlBordeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBordeDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlBordeIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pnlA10;
    private javax.swing.JPanel pnlA11;
    private javax.swing.JPanel pnlA12;
    private javax.swing.JPanel pnlA13;
    private javax.swing.JPanel pnlA14;
    private javax.swing.JPanel pnlA15;
    private javax.swing.JPanel pnlA16;
    private javax.swing.JPanel pnlA17;
    private javax.swing.JPanel pnlA18;
    private javax.swing.JPanel pnlA19;
    private javax.swing.JPanel pnlA20;
    private javax.swing.JPanel pnlA21;
    private javax.swing.JPanel pnlA22;
    private javax.swing.JPanel pnlA23;
    private javax.swing.JPanel pnlA24;
    private javax.swing.JPanel pnlA25;
    private javax.swing.JPanel pnlA26;
    private javax.swing.JPanel pnlA27;
    private javax.swing.JPanel pnlA28;
    private javax.swing.JPanel pnlA29;
    private javax.swing.JPanel pnlA30;
    private javax.swing.JPanel pnlA31;
    private javax.swing.JPanel pnlA32;
    private javax.swing.JPanel pnlA33;
    private javax.swing.JPanel pnlA34;
    private javax.swing.JPanel pnlA35;
    private javax.swing.JPanel pnlA36;
    private javax.swing.JPanel pnlA37;
    private javax.swing.JPanel pnlA38;
    private javax.swing.JPanel pnlA39;
    private javax.swing.JPanel pnlA40;
    private javax.swing.JPanel pnlA8;
    private javax.swing.JPanel pnlA9;
    private javax.swing.JPanel pnlBordeDerecho;
    private javax.swing.JPanel pnlBordeInferior;
    private javax.swing.JPanel pnlBordeIzquierdo;
    private javax.swing.JPanel pnlBordeSuperior;
    private javax.swing.JPanel pnlFondoTablero;
    // End of variables declaration//GEN-END:variables
}
