/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author pc
 */
public class PnlTableroBotones extends javax.swing.JPanel {

    /**
     * Creates new form PnlTableroBotones
     */
    public PnlTableroBotones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoTablero = new javax.swing.JPanel();
        btnH1 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnH5 = new javax.swing.JButton();
        btnH6 = new javax.swing.JButton();
        btnH7 = new javax.swing.JButton();
        btnH8 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        btnG5 = new javax.swing.JButton();
        btnG6 = new javax.swing.JButton();
        btnG7 = new javax.swing.JButton();
        btnG8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnH1.setBorder(null);
        pnlFondoTablero.add(btnH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 70, 70));

        btnH2.setBackground(new java.awt.Color(126, 162, 214));
        btnH2.setBorder(null);
        btnH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 70, 70));

        btnH3.setBorder(null);
        pnlFondoTablero.add(btnH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, 70));

        btnH4.setBackground(new java.awt.Color(126, 162, 214));
        btnH4.setBorder(null);
        pnlFondoTablero.add(btnH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, 70));

        btnH5.setBorder(null);
        pnlFondoTablero.add(btnH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, 70));

        btnH6.setBackground(new java.awt.Color(126, 162, 214));
        btnH6.setBorder(null);
        pnlFondoTablero.add(btnH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 70));

        btnH7.setBorder(null);
        pnlFondoTablero.add(btnH7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, 70));

        btnH8.setBackground(new java.awt.Color(126, 162, 214));
        btnH8.setBorder(null);
        pnlFondoTablero.add(btnH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 70));

        btnG1.setBackground(new java.awt.Color(126, 162, 214));
        btnG1.setBorder(null);
        pnlFondoTablero.add(btnG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 70, 70));

        btnG2.setBorder(null);
        pnlFondoTablero.add(btnG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 70));

        btnG3.setBackground(new java.awt.Color(126, 162, 214));
        btnG3.setBorder(null);
        pnlFondoTablero.add(btnG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 70, 70));

        btnG4.setBorder(null);
        pnlFondoTablero.add(btnG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 70));

        btnG5.setBackground(new java.awt.Color(126, 162, 214));
        btnG5.setBorder(null);
        pnlFondoTablero.add(btnG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 70));

        btnG6.setBorder(null);
        pnlFondoTablero.add(btnG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        btnG7.setBackground(new java.awt.Color(126, 162, 214));
        btnG7.setBorder(null);
        pnlFondoTablero.add(btnG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 70, 70));

        btnG8.setBorder(null);
        pnlFondoTablero.add(btnG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 70));

        add(pnlFondoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void btnH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JButton btnG4;
    private javax.swing.JButton btnG5;
    private javax.swing.JButton btnG6;
    private javax.swing.JButton btnG7;
    private javax.swing.JButton btnG8;
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnH2;
    private javax.swing.JButton btnH3;
    private javax.swing.JButton btnH4;
    private javax.swing.JButton btnH5;
    private javax.swing.JButton btnH6;
    private javax.swing.JButton btnH7;
    private javax.swing.JButton btnH8;
    private javax.swing.JPanel pnlFondoTablero;
    // End of variables declaration//GEN-END:variables
}
