/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author pc
 */
public class PnlTableroBotones extends javax.swing.JPanel{

    static String[][] tablero = new String[8][8];
    static String posicionAntigua;
    static String posicionNueva;
    static String posicionActual;

    public PnlTableroBotones() {
        initComponents();
        iniciarTablero();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoTablero = new javax.swing.JPanel();
        btnH1 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnH5 = new javax.swing.JButton();
        btnH6 = new javax.swing.JButton();
        btnH7 = new javax.swing.JButton();
        btnH8 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        btnG5 = new javax.swing.JButton();
        btnG6 = new javax.swing.JButton();
        btnG7 = new javax.swing.JButton();
        btnG8 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnF2 = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnF5 = new javax.swing.JButton();
        btnF6 = new javax.swing.JButton();
        btnF7 = new javax.swing.JButton();
        btnF8 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnE4 = new javax.swing.JButton();
        btnE5 = new javax.swing.JButton();
        btnE6 = new javax.swing.JButton();
        btnE7 = new javax.swing.JButton();
        btnE8 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnD5 = new javax.swing.JButton();
        btnD6 = new javax.swing.JButton();
        btnD7 = new javax.swing.JButton();
        btnD8 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnC5 = new javax.swing.JButton();
        btnC6 = new javax.swing.JButton();
        btnC7 = new javax.swing.JButton();
        btnC8 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnB5 = new javax.swing.JButton();
        btnB6 = new javax.swing.JButton();
        btnB7 = new javax.swing.JButton();
        btnB8 = new javax.swing.JButton();
        btnA1 = new javax.swing.JButton();
        btnA2 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnA5 = new javax.swing.JButton();
        btnA6 = new javax.swing.JButton();
        btnA7 = new javax.swing.JButton();
        btnA8 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnH1.setBackground(new java.awt.Color(204, 204, 204));
        btnH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreBlanca.png"))); // NOI18N
        btnH1.setBorder(null);
        btnH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 70, 70));

        btnH2.setBackground(new java.awt.Color(126, 162, 214));
        btnH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnH2.setBorder(null);
        btnH2.setBorderPainted(false);
        btnH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH2ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 70, 70));

        btnH3.setBackground(new java.awt.Color(204, 204, 204));
        btnH3.setBorder(null);
        btnH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH3ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, 70));

        btnH4.setBackground(new java.awt.Color(126, 162, 214));
        btnH4.setBorder(null);
        pnlFondoTablero.add(btnH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, 70));

        btnH5.setBackground(new java.awt.Color(204, 204, 204));
        btnH5.setBorder(null);
        pnlFondoTablero.add(btnH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, 70));

        btnH6.setBackground(new java.awt.Color(126, 162, 214));
        btnH6.setBorder(null);
        pnlFondoTablero.add(btnH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 70));

        btnH7.setBackground(new java.awt.Color(204, 204, 204));
        btnH7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnH7.setBorder(null);
        pnlFondoTablero.add(btnH7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, 70));

        btnH8.setBackground(new java.awt.Color(126, 162, 214));
        btnH8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreNegra.png"))); // NOI18N
        btnH8.setBorder(null);
        pnlFondoTablero.add(btnH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 70));

        btnG1.setBackground(new java.awt.Color(126, 162, 214));
        btnG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoBlanco.png"))); // NOI18N
        btnG1.setBorder(null);
        btnG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 70, 70));

        btnG2.setBackground(new java.awt.Color(204, 204, 204));
        btnG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnG2.setBorder(null);
        pnlFondoTablero.add(btnG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 70));

        btnG3.setBackground(new java.awt.Color(126, 162, 214));
        btnG3.setBorder(null);
        pnlFondoTablero.add(btnG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 70, 70));

        btnG4.setBackground(new java.awt.Color(204, 204, 204));
        btnG4.setBorder(null);
        pnlFondoTablero.add(btnG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 70));

        btnG5.setBackground(new java.awt.Color(126, 162, 214));
        btnG5.setBorder(null);
        pnlFondoTablero.add(btnG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 70));

        btnG6.setBackground(new java.awt.Color(204, 204, 204));
        btnG6.setBorder(null);
        pnlFondoTablero.add(btnG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        btnG7.setBackground(new java.awt.Color(126, 162, 214));
        btnG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnG7.setBorder(null);
        pnlFondoTablero.add(btnG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 70, 70));

        btnG8.setBackground(new java.awt.Color(204, 204, 204));
        btnG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoNegro.png"))); // NOI18N
        btnG8.setBorder(null);
        pnlFondoTablero.add(btnG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 70));

        btnF1.setBackground(new java.awt.Color(204, 204, 204));
        btnF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilBlanco.png"))); // NOI18N
        btnF1.setBorder(null);
        btnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 70, 70));

        btnF2.setBackground(new java.awt.Color(126, 162, 214));
        btnF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnF2.setBorder(null);
        pnlFondoTablero.add(btnF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 70));

        btnF3.setBackground(new java.awt.Color(204, 204, 204));
        btnF3.setBorder(null);
        pnlFondoTablero.add(btnF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 70));

        btnF4.setBackground(new java.awt.Color(126, 162, 214));
        btnF4.setBorder(null);
        pnlFondoTablero.add(btnF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 70));

        btnF5.setBackground(new java.awt.Color(204, 204, 204));
        btnF5.setBorder(null);
        pnlFondoTablero.add(btnF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 70));

        btnF6.setBackground(new java.awt.Color(126, 162, 214));
        btnF6.setBorder(null);
        pnlFondoTablero.add(btnF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 70));

        btnF7.setBackground(new java.awt.Color(204, 204, 204));
        btnF7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnF7.setBorder(null);
        pnlFondoTablero.add(btnF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 70));

        btnF8.setBackground(new java.awt.Color(126, 162, 214));
        btnF8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilNegro.png"))); // NOI18N
        btnF8.setBorder(null);
        pnlFondoTablero.add(btnF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 70));

        btnE1.setBackground(new java.awt.Color(126, 162, 214));
        btnE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReyBlanco.png"))); // NOI18N
        btnE1.setBorder(null);
        btnE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 70, 70));

        btnE2.setBackground(new java.awt.Color(204, 204, 204));
        btnE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnE2.setBorder(null);
        pnlFondoTablero.add(btnE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 70, 70));

        btnE3.setBackground(new java.awt.Color(126, 162, 214));
        btnE3.setBorder(null);
        pnlFondoTablero.add(btnE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 70));

        btnE4.setBackground(new java.awt.Color(204, 204, 204));
        btnE4.setBorder(null);
        pnlFondoTablero.add(btnE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 70));

        btnE5.setBackground(new java.awt.Color(126, 162, 214));
        btnE5.setBorder(null);
        pnlFondoTablero.add(btnE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 70));

        btnE6.setBackground(new java.awt.Color(204, 204, 204));
        btnE6.setBorder(null);
        pnlFondoTablero.add(btnE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 70));

        btnE7.setBackground(new java.awt.Color(126, 162, 214));
        btnE7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnE7.setBorder(null);
        pnlFondoTablero.add(btnE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 70));

        btnE8.setBackground(new java.awt.Color(204, 204, 204));
        btnE8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReyNegro.png"))); // NOI18N
        btnE8.setBorder(null);
        pnlFondoTablero.add(btnE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, 70));

        btnD1.setBackground(new java.awt.Color(204, 204, 204));
        btnD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/DamaBlanca.png"))); // NOI18N
        btnD1.setBorder(null);
        btnD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 70, 70));

        btnD2.setBackground(new java.awt.Color(126, 162, 214));
        btnD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnD2.setBorder(null);
        pnlFondoTablero.add(btnD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 70));

        btnD3.setBackground(new java.awt.Color(204, 204, 204));
        btnD3.setBorder(null);
        pnlFondoTablero.add(btnD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, 70));

        btnD4.setBackground(new java.awt.Color(126, 162, 214));
        btnD4.setBorder(null);
        pnlFondoTablero.add(btnD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 70));

        btnD5.setBackground(new java.awt.Color(204, 204, 204));
        btnD5.setBorder(null);
        pnlFondoTablero.add(btnD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, 70));

        btnD6.setBackground(new java.awt.Color(126, 162, 214));
        btnD6.setBorder(null);
        pnlFondoTablero.add(btnD6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 70));

        btnD7.setBackground(new java.awt.Color(204, 204, 204));
        btnD7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnD7.setBorder(null);
        pnlFondoTablero.add(btnD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, 70));

        btnD8.setBackground(new java.awt.Color(126, 162, 214));
        btnD8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/DamaNegra.png"))); // NOI18N
        btnD8.setBorder(null);
        pnlFondoTablero.add(btnD8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 70));

        btnC1.setBackground(new java.awt.Color(126, 162, 214));
        btnC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilBlanco.png"))); // NOI18N
        btnC1.setBorder(null);
        btnC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 70, 70));

        btnC2.setBackground(new java.awt.Color(204, 204, 204));
        btnC2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnC2.setBorder(null);
        pnlFondoTablero.add(btnC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, 70));

        btnC3.setBackground(new java.awt.Color(126, 162, 214));
        btnC3.setBorder(null);
        pnlFondoTablero.add(btnC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 70));

        btnC4.setBackground(new java.awt.Color(204, 204, 204));
        btnC4.setBorder(null);
        pnlFondoTablero.add(btnC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, 70));

        btnC5.setBackground(new java.awt.Color(126, 162, 214));
        btnC5.setBorder(null);
        pnlFondoTablero.add(btnC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 70));

        btnC6.setBackground(new java.awt.Color(204, 204, 204));
        btnC6.setBorder(null);
        pnlFondoTablero.add(btnC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 70));

        btnC7.setBackground(new java.awt.Color(126, 162, 214));
        btnC7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnC7.setBorder(null);
        pnlFondoTablero.add(btnC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 70));

        btnC8.setBackground(new java.awt.Color(204, 204, 204));
        btnC8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilNegro.png"))); // NOI18N
        btnC8.setBorder(null);
        pnlFondoTablero.add(btnC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 70));

        btnB1.setBackground(new java.awt.Color(204, 204, 204));
        btnB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoBlanco.png"))); // NOI18N
        btnB1.setBorder(null);
        btnB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 70, 70));

        btnB2.setBackground(new java.awt.Color(126, 162, 214));
        btnB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnB2.setBorder(null);
        pnlFondoTablero.add(btnB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, 70));

        btnB3.setBackground(new java.awt.Color(204, 204, 204));
        btnB3.setBorder(null);
        pnlFondoTablero.add(btnB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        btnB4.setBackground(new java.awt.Color(126, 162, 214));
        btnB4.setBorder(null);
        pnlFondoTablero.add(btnB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 70));

        btnB5.setBackground(new java.awt.Color(204, 204, 204));
        btnB5.setBorder(null);
        pnlFondoTablero.add(btnB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 70));

        btnB6.setBackground(new java.awt.Color(126, 162, 214));
        btnB6.setBorder(null);
        pnlFondoTablero.add(btnB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 70));

        btnB7.setBackground(new java.awt.Color(204, 204, 204));
        btnB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnB7.setBorder(null);
        pnlFondoTablero.add(btnB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 70));

        btnB8.setBackground(new java.awt.Color(126, 162, 214));
        btnB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoNegro.png"))); // NOI18N
        btnB8.setBorder(null);
        pnlFondoTablero.add(btnB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 70));

        btnA1.setBackground(new java.awt.Color(126, 162, 214));
        btnA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreBlanca.png"))); // NOI18N
        btnA1.setBorder(null);
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });
        pnlFondoTablero.add(btnA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 70));

        btnA2.setBackground(new java.awt.Color(204, 204, 204));
        btnA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        btnA2.setBorder(null);
        pnlFondoTablero.add(btnA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, 70));

        btnA3.setBackground(new java.awt.Color(126, 162, 214));
        btnA3.setBorder(null);
        pnlFondoTablero.add(btnA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, 70));

        btnA4.setBackground(new java.awt.Color(204, 204, 204));
        btnA4.setBorder(null);
        pnlFondoTablero.add(btnA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 70));

        btnA5.setBackground(new java.awt.Color(126, 162, 214));
        btnA5.setBorder(null);
        pnlFondoTablero.add(btnA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 70));

        btnA6.setBackground(new java.awt.Color(204, 204, 204));
        btnA6.setBorder(null);
        pnlFondoTablero.add(btnA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 70));

        btnA7.setBackground(new java.awt.Color(126, 162, 214));
        btnA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        btnA7.setBorder(null);
        pnlFondoTablero.add(btnA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));

        btnA8.setBackground(new java.awt.Color(204, 204, 204));
        btnA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreNegra.png"))); // NOI18N
        btnA8.setBorder(null);
        pnlFondoTablero.add(btnA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        add(pnlFondoTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnB1ActionPerformed

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnD1ActionPerformed

    private void btnE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnE1ActionPerformed

    private void btnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnF1ActionPerformed

    private void btnG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnG1ActionPerformed

    private void btnH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnH1ActionPerformed

    private void btnH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH2ActionPerformed
        posicionActual = getBotonPosicionString(btnH2);
        
    }//GEN-LAST:event_btnH2ActionPerformed

    private void btnH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnH3ActionPerformed
    private String getBotonPosicionString(Object boton) {
        System.out.println("Hola");
        if (boton == btnH2) {
            return "17";
        }
        if (boton == btnH3) {
            return "27";
        }
        return null;
    }

    private void iniciarTablero() {
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                tablero[i][j] = "";
            }
        }
        for (int i = 0; i < 8; i++) {
            tablero[1][i] = "B_peon";
            tablero[6][i] = "A_peon";
        }
        tablero[0][0] = "B_torre";
        tablero[0][1] = "B_caballo";
        tablero[0][2] = "B_alfil";
        tablero[0][3] = "B_reina";
        tablero[0][4] = "B_rey";
        tablero[0][5] = "B_alfil";
        tablero[0][6] = "B_caballo";
        tablero[0][7] = "B_torre";

        tablero[7][0] = "A_torre";
        tablero[7][1] = "A_caballo";
        tablero[7][2] = "A_alfil";
        tablero[7][3] = "A_reina";
        tablero[7][4] = "A_rey";
        tablero[7][5] = "A_alfil";
        tablero[7][6] = "A_caballo";
        tablero[7][7] = "A_torre";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnA1;
    public static javax.swing.JButton btnA2;
    public static javax.swing.JButton btnA3;
    public static javax.swing.JButton btnA4;
    public static javax.swing.JButton btnA5;
    public static javax.swing.JButton btnA6;
    public static javax.swing.JButton btnA7;
    public static javax.swing.JButton btnA8;
    public static javax.swing.JButton btnB1;
    public static javax.swing.JButton btnB2;
    public static javax.swing.JButton btnB3;
    public static javax.swing.JButton btnB4;
    public static javax.swing.JButton btnB5;
    public static javax.swing.JButton btnB6;
    public static javax.swing.JButton btnB7;
    public static javax.swing.JButton btnB8;
    public static javax.swing.JButton btnC1;
    public static javax.swing.JButton btnC2;
    public static javax.swing.JButton btnC3;
    public static javax.swing.JButton btnC4;
    public static javax.swing.JButton btnC5;
    public static javax.swing.JButton btnC6;
    public static javax.swing.JButton btnC7;
    public static javax.swing.JButton btnC8;
    public static javax.swing.JButton btnD1;
    public static javax.swing.JButton btnD2;
    public static javax.swing.JButton btnD3;
    public static javax.swing.JButton btnD4;
    public static javax.swing.JButton btnD5;
    public static javax.swing.JButton btnD6;
    public static javax.swing.JButton btnD7;
    public static javax.swing.JButton btnD8;
    public static javax.swing.JButton btnE1;
    public static javax.swing.JButton btnE2;
    public static javax.swing.JButton btnE3;
    public static javax.swing.JButton btnE4;
    public static javax.swing.JButton btnE5;
    public static javax.swing.JButton btnE6;
    public static javax.swing.JButton btnE7;
    public static javax.swing.JButton btnE8;
    public static javax.swing.JButton btnF1;
    public static javax.swing.JButton btnF2;
    public static javax.swing.JButton btnF3;
    public static javax.swing.JButton btnF4;
    public static javax.swing.JButton btnF5;
    public static javax.swing.JButton btnF6;
    public static javax.swing.JButton btnF7;
    public static javax.swing.JButton btnF8;
    public static javax.swing.JButton btnG1;
    public static javax.swing.JButton btnG2;
    public static javax.swing.JButton btnG3;
    public static javax.swing.JButton btnG4;
    public static javax.swing.JButton btnG5;
    public static javax.swing.JButton btnG6;
    public static javax.swing.JButton btnG7;
    public static javax.swing.JButton btnG8;
    public static javax.swing.JButton btnH1;
    public static javax.swing.JButton btnH2;
    public static javax.swing.JButton btnH3;
    public static javax.swing.JButton btnH4;
    public static javax.swing.JButton btnH5;
    public static javax.swing.JButton btnH6;
    public static javax.swing.JButton btnH7;
    public static javax.swing.JButton btnH8;
    private javax.swing.JPanel pnlFondoTablero;
    // End of variables declaration//GEN-END:variables


}
