/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author pc
 */
public class PnlTablero extends javax.swing.JPanel {

    /**
     * Creates new form PnlTablero
     */
    public PnlTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoTablero = new javax.swing.JPanel();
        pnlA8 = new javax.swing.JPanel();
        lblA8 = new javax.swing.JLabel();
        pnlA7 = new javax.swing.JPanel();
        lblA7 = new javax.swing.JLabel();
        pnlB7 = new javax.swing.JPanel();
        lblB7 = new javax.swing.JLabel();
        pnlB8 = new javax.swing.JPanel();
        lblB8 = new javax.swing.JLabel();
        pnlC7 = new javax.swing.JPanel();
        lblC7 = new javax.swing.JLabel();
        pnlB6 = new javax.swing.JPanel();
        lblB6 = new javax.swing.JLabel();
        pnlC8 = new javax.swing.JPanel();
        lblC8 = new javax.swing.JLabel();
        pnlA6 = new javax.swing.JPanel();
        lblA6 = new javax.swing.JLabel();
        pnlB5 = new javax.swing.JPanel();
        lblB5 = new javax.swing.JLabel();
        pnlD7 = new javax.swing.JPanel();
        lblD7 = new javax.swing.JLabel();
        pnlC6 = new javax.swing.JPanel();
        lblC6 = new javax.swing.JLabel();
        pnlD8 = new javax.swing.JPanel();
        lblD8 = new javax.swing.JLabel();
        pnlD6 = new javax.swing.JPanel();
        lblD6 = new javax.swing.JLabel();
        pnlC5 = new javax.swing.JPanel();
        lblC5 = new javax.swing.JLabel();
        pnlA5 = new javax.swing.JPanel();
        lblA5 = new javax.swing.JLabel();
        pnlB4 = new javax.swing.JPanel();
        lblB4 = new javax.swing.JLabel();
        pnlE7 = new javax.swing.JPanel();
        lblE7 = new javax.swing.JLabel();
        pnlE8 = new javax.swing.JPanel();
        lblE8 = new javax.swing.JLabel();
        pnlE6 = new javax.swing.JPanel();
        lblE6 = new javax.swing.JLabel();
        pnlF7 = new javax.swing.JPanel();
        lblF7 = new javax.swing.JLabel();
        pnlD5 = new javax.swing.JPanel();
        lblD5 = new javax.swing.JLabel();
        pnlC4 = new javax.swing.JPanel();
        lblC4 = new javax.swing.JLabel();
        pnlA4 = new javax.swing.JPanel();
        lblA4 = new javax.swing.JLabel();
        pnlB3 = new javax.swing.JPanel();
        lblB3 = new javax.swing.JLabel();
        pnlA3 = new javax.swing.JPanel();
        lblA3 = new javax.swing.JLabel();
        pnlB2 = new javax.swing.JPanel();
        lblB2 = new javax.swing.JLabel();
        pnlC3 = new javax.swing.JPanel();
        lblC3 = new javax.swing.JLabel();
        pnlD4 = new javax.swing.JPanel();
        lblD4 = new javax.swing.JLabel();
        pnlE5 = new javax.swing.JPanel();
        lblE5 = new javax.swing.JLabel();
        pnlF6 = new javax.swing.JPanel();
        lblF6 = new javax.swing.JLabel();
        pnlF8 = new javax.swing.JPanel();
        lblF8 = new javax.swing.JLabel();
        pnlG7 = new javax.swing.JPanel();
        lblG7 = new javax.swing.JLabel();
        pnlG8 = new javax.swing.JPanel();
        lblG8 = new javax.swing.JLabel();
        pnlH7 = new javax.swing.JPanel();
        lblH7 = new javax.swing.JLabel();
        pnlG6 = new javax.swing.JPanel();
        lblG6 = new javax.swing.JLabel();
        pnlF5 = new javax.swing.JPanel();
        lblF5 = new javax.swing.JLabel();
        pnlE4 = new javax.swing.JPanel();
        lblE4 = new javax.swing.JLabel();
        pnlD3 = new javax.swing.JPanel();
        lblD3 = new javax.swing.JLabel();
        pnlC2 = new javax.swing.JPanel();
        lblC2 = new javax.swing.JLabel();
        pnlB1 = new javax.swing.JPanel();
        lblB1 = new javax.swing.JLabel();
        pnlA2 = new javax.swing.JPanel();
        lblA2 = new javax.swing.JLabel();
        pnlH8 = new javax.swing.JPanel();
        lblH8 = new javax.swing.JLabel();
        pnlH6 = new javax.swing.JPanel();
        lblH6 = new javax.swing.JLabel();
        pnlG5 = new javax.swing.JPanel();
        lblG5 = new javax.swing.JLabel();
        pnlF4 = new javax.swing.JPanel();
        lblF4 = new javax.swing.JLabel();
        pnlE3 = new javax.swing.JPanel();
        lblE3 = new javax.swing.JLabel();
        pnlD2 = new javax.swing.JPanel();
        lblD2 = new javax.swing.JLabel();
        pnlC1 = new javax.swing.JPanel();
        lblC1 = new javax.swing.JLabel();
        pnlA1 = new javax.swing.JPanel();
        lblA1 = new javax.swing.JLabel();
        pnlD1 = new javax.swing.JPanel();
        lblD1 = new javax.swing.JLabel();
        pnlE2 = new javax.swing.JPanel();
        lblE2 = new javax.swing.JLabel();
        pnlF3 = new javax.swing.JPanel();
        lblF3 = new javax.swing.JLabel();
        pnlG4 = new javax.swing.JPanel();
        lblG4 = new javax.swing.JLabel();
        pnlH5 = new javax.swing.JPanel();
        lblH5 = new javax.swing.JLabel();
        pnlA36 = new javax.swing.JPanel();
        pnlH1 = new javax.swing.JPanel();
        lblH1 = new javax.swing.JLabel();
        pnlH2 = new javax.swing.JPanel();
        lblH2 = new javax.swing.JLabel();
        pnlH4 = new javax.swing.JPanel();
        lblH4 = new javax.swing.JLabel();
        pnlG3 = new javax.swing.JPanel();
        lblG3 = new javax.swing.JLabel();
        pnlF2 = new javax.swing.JPanel();
        lblF2 = new javax.swing.JLabel();
        pnlE1 = new javax.swing.JPanel();
        lblE1 = new javax.swing.JLabel();
        pnlG1 = new javax.swing.JPanel();
        lblG1 = new javax.swing.JLabel();
        pnlG2 = new javax.swing.JPanel();
        lblG2 = new javax.swing.JLabel();
        pnlH3 = new javax.swing.JPanel();
        lblH3 = new javax.swing.JLabel();
        pnlF1 = new javax.swing.JPanel();
        lblF1 = new javax.swing.JLabel();
        pnlBordeIzquierdo = new javax.swing.JPanel();
        pnlBordeSuperior = new javax.swing.JPanel();
        pnlBordeDerecho = new javax.swing.JPanel();
        pnlBordeInferior = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlFondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlA8.setBackground(new java.awt.Color(255, 255, 255));

        lblA8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreBlanca.png"))); // NOI18N
        pnlA8.add(lblA8);

        pnlFondoTablero.add(pnlA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 70, 70));

        pnlA7.setBackground(new java.awt.Color(126, 162, 214));

        lblA7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoBlanco.png"))); // NOI18N
        pnlA7.add(lblA7);

        pnlFondoTablero.add(pnlA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 70, 70));

        pnlB7.setBackground(new java.awt.Color(255, 255, 255));

        lblB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB7.add(lblB7);

        pnlFondoTablero.add(pnlB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 70));

        pnlB8.setBackground(new java.awt.Color(126, 162, 214));

        lblB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB8.add(lblB8);

        pnlFondoTablero.add(pnlB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 70, 70));

        pnlC7.setBackground(new java.awt.Color(126, 162, 214));
        pnlC7.add(lblC7);

        pnlFondoTablero.add(pnlC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 70, 70));

        pnlB6.setBackground(new java.awt.Color(126, 162, 214));

        lblB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB6.add(lblB6);

        pnlFondoTablero.add(pnlB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 70));

        pnlC8.setBackground(new java.awt.Color(255, 255, 255));
        pnlC8.add(lblC8);

        pnlFondoTablero.add(pnlC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, 70));

        pnlA6.setBackground(new java.awt.Color(255, 255, 255));

        lblA6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilBlanco.png"))); // NOI18N
        pnlA6.add(lblA6);

        pnlFondoTablero.add(pnlA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 70, 70));

        pnlB5.setBackground(new java.awt.Color(255, 255, 255));

        lblB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB5.add(lblB5);

        pnlFondoTablero.add(pnlB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 70, 70));

        pnlD7.setBackground(new java.awt.Color(255, 255, 255));
        pnlD7.add(lblD7);

        pnlFondoTablero.add(pnlD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 70));

        pnlC6.setBackground(new java.awt.Color(255, 255, 255));
        pnlC6.add(lblC6);

        pnlFondoTablero.add(pnlC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 70));

        pnlD8.setBackground(new java.awt.Color(126, 162, 214));
        pnlD8.add(lblD8);

        pnlFondoTablero.add(pnlD8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, 70));

        pnlD6.setBackground(new java.awt.Color(126, 162, 214));
        pnlD6.add(lblD6);

        pnlFondoTablero.add(pnlD6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 70));

        pnlC5.setBackground(new java.awt.Color(126, 162, 214));
        pnlC5.add(lblC5);

        pnlFondoTablero.add(pnlC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 70));

        pnlA5.setBackground(new java.awt.Color(126, 162, 214));

        lblA5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReyBlanco.png"))); // NOI18N
        pnlA5.add(lblA5);

        pnlFondoTablero.add(pnlA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 70, 70));

        pnlB4.setBackground(new java.awt.Color(126, 162, 214));

        lblB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB4.add(lblB4);

        pnlFondoTablero.add(pnlB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 70));

        pnlE7.setBackground(new java.awt.Color(126, 162, 214));
        pnlE7.add(lblE7);

        pnlFondoTablero.add(pnlE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 70));

        pnlE8.setBackground(new java.awt.Color(255, 255, 255));
        pnlE8.add(lblE8);

        pnlFondoTablero.add(pnlE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, 70));

        pnlE6.setBackground(new java.awt.Color(255, 255, 255));
        pnlE6.add(lblE6);

        pnlFondoTablero.add(pnlE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 70));

        pnlF7.setBackground(new java.awt.Color(255, 255, 255));
        pnlF7.add(lblF7);

        pnlFondoTablero.add(pnlF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        pnlD5.setBackground(new java.awt.Color(255, 255, 255));
        pnlD5.add(lblD5);

        pnlFondoTablero.add(pnlD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 70));

        pnlC4.setBackground(new java.awt.Color(255, 255, 255));
        pnlC4.add(lblC4);

        pnlFondoTablero.add(pnlC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, 70));

        pnlA4.setBackground(new java.awt.Color(255, 255, 255));

        lblA4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/DamaBlanca.png"))); // NOI18N
        pnlA4.add(lblA4);

        pnlFondoTablero.add(pnlA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 70, 70));

        pnlB3.setBackground(new java.awt.Color(255, 255, 255));

        lblB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB3.add(lblB3);

        pnlFondoTablero.add(pnlB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, 70));

        pnlA3.setBackground(new java.awt.Color(126, 162, 214));

        lblA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilBlanco.png"))); // NOI18N
        pnlA3.add(lblA3);

        pnlFondoTablero.add(pnlA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 70, 70));

        pnlB2.setBackground(new java.awt.Color(126, 162, 214));

        lblB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB2.add(lblB2);

        pnlFondoTablero.add(pnlB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, 70));

        pnlC3.setBackground(new java.awt.Color(126, 162, 214));
        pnlC3.add(lblC3);

        pnlFondoTablero.add(pnlC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 70));

        pnlD4.setBackground(new java.awt.Color(126, 162, 214));
        pnlD4.add(lblD4);

        pnlFondoTablero.add(pnlD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 70));

        pnlE5.setBackground(new java.awt.Color(126, 162, 214));
        pnlE5.add(lblE5);

        pnlFondoTablero.add(pnlE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 70));

        pnlF6.setBackground(new java.awt.Color(126, 162, 214));
        pnlF6.add(lblF6);

        pnlFondoTablero.add(pnlF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 70));

        pnlF8.setBackground(new java.awt.Color(126, 162, 214));
        pnlF8.add(lblF8);

        pnlFondoTablero.add(pnlF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 70));

        pnlG7.setBackground(new java.awt.Color(126, 162, 214));

        lblG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG7.add(lblG7);

        pnlFondoTablero.add(pnlG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 70, 70));

        pnlG8.setBackground(new java.awt.Color(255, 255, 255));

        lblG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG8.add(lblG8);

        pnlFondoTablero.add(pnlG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, 70));

        pnlH7.setBackground(new java.awt.Color(255, 255, 255));

        lblH7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoNegro.png"))); // NOI18N
        pnlH7.add(lblH7);

        pnlFondoTablero.add(pnlH7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 70));

        pnlG6.setBackground(new java.awt.Color(255, 255, 255));

        lblG6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG6.add(lblG6);

        pnlFondoTablero.add(pnlG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 70));

        pnlF5.setBackground(new java.awt.Color(255, 255, 255));
        pnlF5.add(lblF5);

        pnlFondoTablero.add(pnlF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 70));

        pnlE4.setBackground(new java.awt.Color(255, 255, 255));
        pnlE4.add(lblE4);

        pnlFondoTablero.add(pnlE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, 70));

        pnlD3.setBackground(new java.awt.Color(255, 255, 255));
        pnlD3.add(lblD3);

        pnlFondoTablero.add(pnlD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, 70));

        pnlC2.setBackground(new java.awt.Color(255, 255, 255));
        pnlC2.add(lblC2);

        pnlFondoTablero.add(pnlC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        pnlB1.setBackground(new java.awt.Color(255, 255, 255));
        pnlB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlB1MouseClicked(evt);
            }
        });

        lblB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónBlanco.png"))); // NOI18N
        pnlB1.add(lblB1);

        pnlFondoTablero.add(pnlB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, 70));

        pnlA2.setBackground(new java.awt.Color(255, 255, 255));

        lblA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoBlanco.png"))); // NOI18N
        pnlA2.add(lblA2);

        pnlFondoTablero.add(pnlA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 70, 70));

        pnlH8.setBackground(new java.awt.Color(126, 162, 214));

        lblH8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreNegra.png"))); // NOI18N
        pnlH8.add(lblH8);

        pnlFondoTablero.add(pnlH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 70));

        pnlH6.setBackground(new java.awt.Color(126, 162, 214));

        lblH6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilNegro.png"))); // NOI18N
        pnlH6.add(lblH6);

        pnlFondoTablero.add(pnlH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 70));

        pnlG5.setBackground(new java.awt.Color(126, 162, 214));

        lblG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG5.add(lblG5);

        pnlFondoTablero.add(pnlG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 70));

        pnlF4.setBackground(new java.awt.Color(126, 162, 214));
        pnlF4.add(lblF4);

        pnlFondoTablero.add(pnlF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 70));

        pnlE3.setBackground(new java.awt.Color(126, 162, 214));
        pnlE3.add(lblE3);

        pnlFondoTablero.add(pnlE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 70));

        pnlD2.setBackground(new java.awt.Color(126, 162, 214));
        pnlD2.add(lblD2);

        pnlFondoTablero.add(pnlD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 70));

        pnlC1.setBackground(new java.awt.Color(126, 162, 214));
        pnlC1.add(lblC1);

        pnlFondoTablero.add(pnlC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, 70));

        pnlA1.setBackground(new java.awt.Color(126, 162, 214));

        lblA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreBlanca.png"))); // NOI18N
        pnlA1.add(lblA1);

        pnlFondoTablero.add(pnlA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 70));

        pnlD1.setBackground(new java.awt.Color(255, 255, 255));
        pnlD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlD1MouseClicked(evt);
            }
        });
        pnlD1.add(lblD1);

        pnlFondoTablero.add(pnlD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 70));

        pnlE2.setBackground(new java.awt.Color(255, 255, 255));
        pnlE2.add(lblE2);

        pnlFondoTablero.add(pnlE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 70));

        pnlF3.setBackground(new java.awt.Color(255, 255, 255));
        pnlF3.add(lblF3);

        pnlFondoTablero.add(pnlF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 70));

        pnlG4.setBackground(new java.awt.Color(255, 255, 255));

        lblG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG4.add(lblG4);

        pnlFondoTablero.add(pnlG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, 70));

        pnlH5.setBackground(new java.awt.Color(255, 255, 255));

        lblH5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ReyNegro.png"))); // NOI18N
        pnlH5.add(lblH5);

        pnlFondoTablero.add(pnlH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, 70));

        pnlA36.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA36Layout = new javax.swing.GroupLayout(pnlA36);
        pnlA36.setLayout(pnlA36Layout);
        pnlA36Layout.setHorizontalGroup(
            pnlA36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA36Layout.setVerticalGroup(
            pnlA36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        pnlH1.setBackground(new java.awt.Color(255, 255, 255));

        lblH1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/TorreNegra.png"))); // NOI18N
        pnlH1.add(lblH1);

        pnlFondoTablero.add(pnlH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        pnlH2.setBackground(new java.awt.Color(126, 162, 214));

        lblH2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/CaballoNegro.png"))); // NOI18N
        pnlH2.add(lblH2);

        pnlFondoTablero.add(pnlH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 70));

        pnlH4.setBackground(new java.awt.Color(126, 162, 214));

        lblH4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/DamaNegra.png"))); // NOI18N
        pnlH4.add(lblH4);

        pnlFondoTablero.add(pnlH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 70));

        pnlG3.setBackground(new java.awt.Color(126, 162, 214));

        lblG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG3.add(lblG3);

        pnlFondoTablero.add(pnlG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 70));

        pnlF2.setBackground(new java.awt.Color(126, 162, 214));
        pnlF2.add(lblF2);

        pnlFondoTablero.add(pnlF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 70));

        pnlE1.setBackground(new java.awt.Color(126, 162, 214));
        pnlE1.add(lblE1);

        pnlFondoTablero.add(pnlE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 70));

        pnlG1.setBackground(new java.awt.Color(126, 162, 214));

        lblG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG1.add(lblG1);

        pnlFondoTablero.add(pnlG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));

        pnlG2.setBackground(new java.awt.Color(255, 255, 255));

        lblG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/PeónNegro.png"))); // NOI18N
        pnlG2.add(lblG2);

        pnlFondoTablero.add(pnlG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 70));

        pnlH3.setBackground(new java.awt.Color(255, 255, 255));

        lblH3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/AlfilNegro.png"))); // NOI18N
        pnlH3.add(lblH3);

        pnlFondoTablero.add(pnlH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 70));

        pnlF1.setBackground(new java.awt.Color(255, 255, 255));
        pnlF1.add(lblF1);

        pnlFondoTablero.add(pnlF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 70));

        pnlBordeIzquierdo.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeIzquierdoLayout = new javax.swing.GroupLayout(pnlBordeIzquierdo);
        pnlBordeIzquierdo.setLayout(pnlBordeIzquierdoLayout);
        pnlBordeIzquierdoLayout.setHorizontalGroup(
            pnlBordeIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlBordeIzquierdoLayout.setVerticalGroup(
            pnlBordeIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlBordeSuperior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeSuperiorLayout = new javax.swing.GroupLayout(pnlBordeSuperior);
        pnlBordeSuperior.setLayout(pnlBordeSuperiorLayout);
        pnlBordeSuperiorLayout.setHorizontalGroup(
            pnlBordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlBordeSuperiorLayout.setVerticalGroup(
            pnlBordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBordeDerecho.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeDerechoLayout = new javax.swing.GroupLayout(pnlBordeDerecho);
        pnlBordeDerecho.setLayout(pnlBordeDerechoLayout);
        pnlBordeDerechoLayout.setHorizontalGroup(
            pnlBordeDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlBordeDerechoLayout.setVerticalGroup(
            pnlBordeDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlBordeInferior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeInferiorLayout = new javax.swing.GroupLayout(pnlBordeInferior);
        pnlBordeInferior.setLayout(pnlBordeInferiorLayout);
        pnlBordeInferiorLayout.setHorizontalGroup(
            pnlBordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlBordeInferiorLayout.setVerticalGroup(
            pnlBordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlBordeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBordeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBordeDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBordeIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBordeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(pnlBordeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBordeDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlBordeIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlB1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnlB1MouseClicked

    private void pnlD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlD1MouseClicked
        // TODO add your handling code here:
        lblD1.setIcon(lblB1.getIcon());
        lblB1.setIcon(null);
    }//GEN-LAST:event_pnlD1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblA1;
    private javax.swing.JLabel lblA2;
    private javax.swing.JLabel lblA3;
    private javax.swing.JLabel lblA4;
    private javax.swing.JLabel lblA5;
    private javax.swing.JLabel lblA6;
    private javax.swing.JLabel lblA7;
    private javax.swing.JLabel lblA8;
    private javax.swing.JLabel lblB1;
    private javax.swing.JLabel lblB2;
    private javax.swing.JLabel lblB3;
    private javax.swing.JLabel lblB4;
    private javax.swing.JLabel lblB5;
    private javax.swing.JLabel lblB6;
    private javax.swing.JLabel lblB7;
    public static javax.swing.JLabel lblB8;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblC6;
    private javax.swing.JLabel lblC7;
    private javax.swing.JLabel lblC8;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblD2;
    private javax.swing.JLabel lblD3;
    private javax.swing.JLabel lblD4;
    private javax.swing.JLabel lblD5;
    private javax.swing.JLabel lblD6;
    private javax.swing.JLabel lblD7;
    private javax.swing.JLabel lblD8;
    private javax.swing.JLabel lblE1;
    private javax.swing.JLabel lblE2;
    private javax.swing.JLabel lblE3;
    private javax.swing.JLabel lblE4;
    private javax.swing.JLabel lblE5;
    private javax.swing.JLabel lblE6;
    private javax.swing.JLabel lblE7;
    private javax.swing.JLabel lblE8;
    private javax.swing.JLabel lblF1;
    private javax.swing.JLabel lblF2;
    private javax.swing.JLabel lblF3;
    private javax.swing.JLabel lblF4;
    private javax.swing.JLabel lblF5;
    private javax.swing.JLabel lblF6;
    private javax.swing.JLabel lblF7;
    private javax.swing.JLabel lblF8;
    private javax.swing.JLabel lblG1;
    private javax.swing.JLabel lblG2;
    private javax.swing.JLabel lblG3;
    private javax.swing.JLabel lblG4;
    private javax.swing.JLabel lblG5;
    private javax.swing.JLabel lblG6;
    private javax.swing.JLabel lblG7;
    private javax.swing.JLabel lblG8;
    private javax.swing.JLabel lblH1;
    private javax.swing.JLabel lblH2;
    private javax.swing.JLabel lblH3;
    private javax.swing.JLabel lblH4;
    private javax.swing.JLabel lblH5;
    private javax.swing.JLabel lblH6;
    private javax.swing.JLabel lblH7;
    private javax.swing.JLabel lblH8;
    private javax.swing.JPanel pnlA1;
    private javax.swing.JPanel pnlA2;
    private javax.swing.JPanel pnlA3;
    private javax.swing.JPanel pnlA36;
    private javax.swing.JPanel pnlA4;
    private javax.swing.JPanel pnlA5;
    private javax.swing.JPanel pnlA6;
    private javax.swing.JPanel pnlA7;
    private javax.swing.JPanel pnlA8;
    private javax.swing.JPanel pnlB1;
    private javax.swing.JPanel pnlB2;
    private javax.swing.JPanel pnlB3;
    private javax.swing.JPanel pnlB4;
    private javax.swing.JPanel pnlB5;
    private javax.swing.JPanel pnlB6;
    private javax.swing.JPanel pnlB7;
    public static javax.swing.JPanel pnlB8;
    private javax.swing.JPanel pnlBordeDerecho;
    private javax.swing.JPanel pnlBordeInferior;
    private javax.swing.JPanel pnlBordeIzquierdo;
    private javax.swing.JPanel pnlBordeSuperior;
    private javax.swing.JPanel pnlC1;
    private javax.swing.JPanel pnlC2;
    private javax.swing.JPanel pnlC3;
    private javax.swing.JPanel pnlC4;
    private javax.swing.JPanel pnlC5;
    private javax.swing.JPanel pnlC6;
    private javax.swing.JPanel pnlC7;
    private javax.swing.JPanel pnlC8;
    private javax.swing.JPanel pnlD1;
    private javax.swing.JPanel pnlD2;
    private javax.swing.JPanel pnlD3;
    private javax.swing.JPanel pnlD4;
    private javax.swing.JPanel pnlD5;
    private javax.swing.JPanel pnlD6;
    private javax.swing.JPanel pnlD7;
    private javax.swing.JPanel pnlD8;
    private javax.swing.JPanel pnlE1;
    private javax.swing.JPanel pnlE2;
    private javax.swing.JPanel pnlE3;
    private javax.swing.JPanel pnlE4;
    private javax.swing.JPanel pnlE5;
    private javax.swing.JPanel pnlE6;
    private javax.swing.JPanel pnlE7;
    private javax.swing.JPanel pnlE8;
    private javax.swing.JPanel pnlF1;
    private javax.swing.JPanel pnlF2;
    private javax.swing.JPanel pnlF3;
    private javax.swing.JPanel pnlF4;
    private javax.swing.JPanel pnlF5;
    private javax.swing.JPanel pnlF6;
    private javax.swing.JPanel pnlF7;
    private javax.swing.JPanel pnlF8;
    private javax.swing.JPanel pnlFondoTablero;
    private javax.swing.JPanel pnlG1;
    private javax.swing.JPanel pnlG2;
    private javax.swing.JPanel pnlG3;
    private javax.swing.JPanel pnlG4;
    private javax.swing.JPanel pnlG5;
    private javax.swing.JPanel pnlG6;
    private javax.swing.JPanel pnlG7;
    private javax.swing.JPanel pnlG8;
    private javax.swing.JPanel pnlH1;
    private javax.swing.JPanel pnlH2;
    private javax.swing.JPanel pnlH3;
    private javax.swing.JPanel pnlH4;
    private javax.swing.JPanel pnlH5;
    private javax.swing.JPanel pnlH6;
    private javax.swing.JPanel pnlH7;
    private javax.swing.JPanel pnlH8;
    // End of variables declaration//GEN-END:variables
}
