/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author pc
 */
public class PnlTablero extends javax.swing.JPanel {

    /**
     * Creates new form PnlTablero
     */
    public PnlTablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondoTablero = new javax.swing.JPanel();
        pnlA8 = new javax.swing.JPanel();
        pnlA7 = new javax.swing.JPanel();
        pnlB7 = new javax.swing.JPanel();
        pnlB8 = new javax.swing.JPanel();
        pnlC7 = new javax.swing.JPanel();
        pnlB6 = new javax.swing.JPanel();
        pnlC8 = new javax.swing.JPanel();
        pnlA6 = new javax.swing.JPanel();
        pnlB5 = new javax.swing.JPanel();
        pnlD7 = new javax.swing.JPanel();
        pnlC6 = new javax.swing.JPanel();
        pnlD8 = new javax.swing.JPanel();
        pnlD6 = new javax.swing.JPanel();
        pnlC5 = new javax.swing.JPanel();
        pnlA5 = new javax.swing.JPanel();
        pnlB4 = new javax.swing.JPanel();
        pnlE7 = new javax.swing.JPanel();
        pnlE8 = new javax.swing.JPanel();
        pnlE6 = new javax.swing.JPanel();
        pnlF7 = new javax.swing.JPanel();
        pnlD5 = new javax.swing.JPanel();
        pnlC4 = new javax.swing.JPanel();
        pnlA4 = new javax.swing.JPanel();
        pnlB3 = new javax.swing.JPanel();
        pnlA3 = new javax.swing.JPanel();
        pnlB2 = new javax.swing.JPanel();
        pnlC3 = new javax.swing.JPanel();
        pnlD4 = new javax.swing.JPanel();
        pnlE5 = new javax.swing.JPanel();
        pnlF6 = new javax.swing.JPanel();
        pnlF8 = new javax.swing.JPanel();
        pnlG7 = new javax.swing.JPanel();
        pnlG8 = new javax.swing.JPanel();
        pnlH7 = new javax.swing.JPanel();
        pnlG6 = new javax.swing.JPanel();
        pnlF5 = new javax.swing.JPanel();
        pnlE4 = new javax.swing.JPanel();
        pnlD3 = new javax.swing.JPanel();
        pnlC2 = new javax.swing.JPanel();
        pnlB1 = new javax.swing.JPanel();
        pnlA2 = new javax.swing.JPanel();
        pnlH8 = new javax.swing.JPanel();
        pnlH6 = new javax.swing.JPanel();
        pnlG5 = new javax.swing.JPanel();
        pnlF4 = new javax.swing.JPanel();
        pnlE3 = new javax.swing.JPanel();
        pnlD2 = new javax.swing.JPanel();
        pnlC1 = new javax.swing.JPanel();
        pnlA1 = new javax.swing.JPanel();
        pnlD1 = new javax.swing.JPanel();
        pnlE2 = new javax.swing.JPanel();
        pnlF3 = new javax.swing.JPanel();
        pnlG4 = new javax.swing.JPanel();
        pnlH5 = new javax.swing.JPanel();
        pnlA36 = new javax.swing.JPanel();
        pnlH1 = new javax.swing.JPanel();
        pnlH2 = new javax.swing.JPanel();
        pnlH4 = new javax.swing.JPanel();
        pnlG3 = new javax.swing.JPanel();
        pnlF2 = new javax.swing.JPanel();
        pnlE1 = new javax.swing.JPanel();
        pnlG1 = new javax.swing.JPanel();
        pnlG2 = new javax.swing.JPanel();
        pnlH3 = new javax.swing.JPanel();
        pnlF1 = new javax.swing.JPanel();
        pnlBordeIzquierdo = new javax.swing.JPanel();
        pnlBordeSuperior = new javax.swing.JPanel();
        pnlBordeDerecho = new javax.swing.JPanel();
        pnlBordeInferior = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlFondoTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlA8.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoTablero.add(pnlA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 70, 70));

        pnlA7.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlA7Layout = new javax.swing.GroupLayout(pnlA7);
        pnlA7.setLayout(pnlA7Layout);
        pnlA7Layout.setHorizontalGroup(
            pnlA7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA7Layout.setVerticalGroup(
            pnlA7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 70, 70));

        pnlB7.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoTablero.add(pnlB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 70, 70));

        pnlB8.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlB8Layout = new javax.swing.GroupLayout(pnlB8);
        pnlB8.setLayout(pnlB8Layout);
        pnlB8Layout.setHorizontalGroup(
            pnlB8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB8Layout.setVerticalGroup(
            pnlB8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 70, 70));

        pnlC7.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlC7Layout = new javax.swing.GroupLayout(pnlC7);
        pnlC7.setLayout(pnlC7Layout);
        pnlC7Layout.setHorizontalGroup(
            pnlC7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC7Layout.setVerticalGroup(
            pnlC7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 70, 70));

        pnlB6.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlB6Layout = new javax.swing.GroupLayout(pnlB6);
        pnlB6.setLayout(pnlB6Layout);
        pnlB6Layout.setHorizontalGroup(
            pnlB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB6Layout.setVerticalGroup(
            pnlB6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 70, 70));

        pnlC8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlC8Layout = new javax.swing.GroupLayout(pnlC8);
        pnlC8.setLayout(pnlC8Layout);
        pnlC8Layout.setHorizontalGroup(
            pnlC8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC8Layout.setVerticalGroup(
            pnlC8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 70, 70));

        pnlA6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA6Layout = new javax.swing.GroupLayout(pnlA6);
        pnlA6.setLayout(pnlA6Layout);
        pnlA6Layout.setHorizontalGroup(
            pnlA6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA6Layout.setVerticalGroup(
            pnlA6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 70, 70));

        pnlB5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlB5Layout = new javax.swing.GroupLayout(pnlB5);
        pnlB5.setLayout(pnlB5Layout);
        pnlB5Layout.setHorizontalGroup(
            pnlB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB5Layout.setVerticalGroup(
            pnlB5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 70, 70));

        pnlD7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlD7Layout = new javax.swing.GroupLayout(pnlD7);
        pnlD7.setLayout(pnlD7Layout);
        pnlD7Layout.setHorizontalGroup(
            pnlD7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD7Layout.setVerticalGroup(
            pnlD7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 70, 70));

        pnlC6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlC6Layout = new javax.swing.GroupLayout(pnlC6);
        pnlC6.setLayout(pnlC6Layout);
        pnlC6Layout.setHorizontalGroup(
            pnlC6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC6Layout.setVerticalGroup(
            pnlC6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 70, 70));

        pnlD8.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlD8Layout = new javax.swing.GroupLayout(pnlD8);
        pnlD8.setLayout(pnlD8Layout);
        pnlD8Layout.setHorizontalGroup(
            pnlD8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD8Layout.setVerticalGroup(
            pnlD8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 70, 70));

        pnlD6.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlD6Layout = new javax.swing.GroupLayout(pnlD6);
        pnlD6.setLayout(pnlD6Layout);
        pnlD6Layout.setHorizontalGroup(
            pnlD6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD6Layout.setVerticalGroup(
            pnlD6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 70, 70));

        pnlC5.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlC5Layout = new javax.swing.GroupLayout(pnlC5);
        pnlC5.setLayout(pnlC5Layout);
        pnlC5Layout.setHorizontalGroup(
            pnlC5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC5Layout.setVerticalGroup(
            pnlC5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 70, 70));

        pnlA5.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlA5Layout = new javax.swing.GroupLayout(pnlA5);
        pnlA5.setLayout(pnlA5Layout);
        pnlA5Layout.setHorizontalGroup(
            pnlA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA5Layout.setVerticalGroup(
            pnlA5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 70, 70));

        pnlB4.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlB4Layout = new javax.swing.GroupLayout(pnlB4);
        pnlB4.setLayout(pnlB4Layout);
        pnlB4Layout.setHorizontalGroup(
            pnlB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB4Layout.setVerticalGroup(
            pnlB4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 70));

        pnlE7.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlE7Layout = new javax.swing.GroupLayout(pnlE7);
        pnlE7.setLayout(pnlE7Layout);
        pnlE7Layout.setHorizontalGroup(
            pnlE7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE7Layout.setVerticalGroup(
            pnlE7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 70, 70));

        pnlE8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlE8Layout = new javax.swing.GroupLayout(pnlE8);
        pnlE8.setLayout(pnlE8Layout);
        pnlE8Layout.setHorizontalGroup(
            pnlE8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE8Layout.setVerticalGroup(
            pnlE8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 70, 70));

        pnlE6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlE6Layout = new javax.swing.GroupLayout(pnlE6);
        pnlE6.setLayout(pnlE6Layout);
        pnlE6Layout.setHorizontalGroup(
            pnlE6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE6Layout.setVerticalGroup(
            pnlE6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 70, 70));

        pnlF7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlF7Layout = new javax.swing.GroupLayout(pnlF7);
        pnlF7.setLayout(pnlF7Layout);
        pnlF7Layout.setHorizontalGroup(
            pnlF7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF7Layout.setVerticalGroup(
            pnlF7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 70, 70));

        pnlD5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlD5Layout = new javax.swing.GroupLayout(pnlD5);
        pnlD5.setLayout(pnlD5Layout);
        pnlD5Layout.setHorizontalGroup(
            pnlD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD5Layout.setVerticalGroup(
            pnlD5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 70, 70));

        pnlC4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlC4Layout = new javax.swing.GroupLayout(pnlC4);
        pnlC4.setLayout(pnlC4Layout);
        pnlC4Layout.setHorizontalGroup(
            pnlC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC4Layout.setVerticalGroup(
            pnlC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 70, 70));

        pnlA4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA4Layout = new javax.swing.GroupLayout(pnlA4);
        pnlA4.setLayout(pnlA4Layout);
        pnlA4Layout.setHorizontalGroup(
            pnlA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA4Layout.setVerticalGroup(
            pnlA4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 70, 70));

        pnlB3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlB3Layout = new javax.swing.GroupLayout(pnlB3);
        pnlB3.setLayout(pnlB3Layout);
        pnlB3Layout.setHorizontalGroup(
            pnlB3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB3Layout.setVerticalGroup(
            pnlB3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, 70));

        pnlA3.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlA3Layout = new javax.swing.GroupLayout(pnlA3);
        pnlA3.setLayout(pnlA3Layout);
        pnlA3Layout.setHorizontalGroup(
            pnlA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA3Layout.setVerticalGroup(
            pnlA3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 70, 70));

        pnlB2.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlB2Layout = new javax.swing.GroupLayout(pnlB2);
        pnlB2.setLayout(pnlB2Layout);
        pnlB2Layout.setHorizontalGroup(
            pnlB2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB2Layout.setVerticalGroup(
            pnlB2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, 70));

        pnlC3.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlC3Layout = new javax.swing.GroupLayout(pnlC3);
        pnlC3.setLayout(pnlC3Layout);
        pnlC3Layout.setHorizontalGroup(
            pnlC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC3Layout.setVerticalGroup(
            pnlC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 70, 70));

        pnlD4.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlD4Layout = new javax.swing.GroupLayout(pnlD4);
        pnlD4.setLayout(pnlD4Layout);
        pnlD4Layout.setHorizontalGroup(
            pnlD4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD4Layout.setVerticalGroup(
            pnlD4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, 70));

        pnlE5.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlE5Layout = new javax.swing.GroupLayout(pnlE5);
        pnlE5.setLayout(pnlE5Layout);
        pnlE5Layout.setHorizontalGroup(
            pnlE5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE5Layout.setVerticalGroup(
            pnlE5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 70, 70));

        pnlF6.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlF6Layout = new javax.swing.GroupLayout(pnlF6);
        pnlF6.setLayout(pnlF6Layout);
        pnlF6Layout.setHorizontalGroup(
            pnlF6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF6Layout.setVerticalGroup(
            pnlF6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 70, 70));

        pnlF8.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlF8Layout = new javax.swing.GroupLayout(pnlF8);
        pnlF8.setLayout(pnlF8Layout);
        pnlF8Layout.setHorizontalGroup(
            pnlF8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF8Layout.setVerticalGroup(
            pnlF8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 70, 70));

        pnlG7.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlG7Layout = new javax.swing.GroupLayout(pnlG7);
        pnlG7.setLayout(pnlG7Layout);
        pnlG7Layout.setHorizontalGroup(
            pnlG7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG7Layout.setVerticalGroup(
            pnlG7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 70, 70));

        pnlG8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlG8Layout = new javax.swing.GroupLayout(pnlG8);
        pnlG8.setLayout(pnlG8Layout);
        pnlG8Layout.setHorizontalGroup(
            pnlG8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG8Layout.setVerticalGroup(
            pnlG8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 70, 70));

        pnlH7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlH7Layout = new javax.swing.GroupLayout(pnlH7);
        pnlH7.setLayout(pnlH7Layout);
        pnlH7Layout.setHorizontalGroup(
            pnlH7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH7Layout.setVerticalGroup(
            pnlH7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 70));

        pnlG6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlG6Layout = new javax.swing.GroupLayout(pnlG6);
        pnlG6.setLayout(pnlG6Layout);
        pnlG6Layout.setHorizontalGroup(
            pnlG6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG6Layout.setVerticalGroup(
            pnlG6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 70));

        pnlF5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlF5Layout = new javax.swing.GroupLayout(pnlF5);
        pnlF5.setLayout(pnlF5Layout);
        pnlF5Layout.setHorizontalGroup(
            pnlF5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF5Layout.setVerticalGroup(
            pnlF5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 70, 70));

        pnlE4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlE4Layout = new javax.swing.GroupLayout(pnlE4);
        pnlE4.setLayout(pnlE4Layout);
        pnlE4Layout.setHorizontalGroup(
            pnlE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE4Layout.setVerticalGroup(
            pnlE4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, 70));

        pnlD3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlD3Layout = new javax.swing.GroupLayout(pnlD3);
        pnlD3.setLayout(pnlD3Layout);
        pnlD3Layout.setHorizontalGroup(
            pnlD3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD3Layout.setVerticalGroup(
            pnlD3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, 70));

        pnlC2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlC2Layout = new javax.swing.GroupLayout(pnlC2);
        pnlC2.setLayout(pnlC2Layout);
        pnlC2Layout.setHorizontalGroup(
            pnlC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC2Layout.setVerticalGroup(
            pnlC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        pnlB1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlB1Layout = new javax.swing.GroupLayout(pnlB1);
        pnlB1.setLayout(pnlB1Layout);
        pnlB1Layout.setHorizontalGroup(
            pnlB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlB1Layout.setVerticalGroup(
            pnlB1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 70, 70));

        pnlA2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA2Layout = new javax.swing.GroupLayout(pnlA2);
        pnlA2.setLayout(pnlA2Layout);
        pnlA2Layout.setHorizontalGroup(
            pnlA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA2Layout.setVerticalGroup(
            pnlA2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 70, 70));

        pnlH8.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlH8Layout = new javax.swing.GroupLayout(pnlH8);
        pnlH8.setLayout(pnlH8Layout);
        pnlH8Layout.setHorizontalGroup(
            pnlH8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH8Layout.setVerticalGroup(
            pnlH8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 70, 70));

        pnlH6.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlH6Layout = new javax.swing.GroupLayout(pnlH6);
        pnlH6.setLayout(pnlH6Layout);
        pnlH6Layout.setHorizontalGroup(
            pnlH6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH6Layout.setVerticalGroup(
            pnlH6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 70));

        pnlG5.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlG5Layout = new javax.swing.GroupLayout(pnlG5);
        pnlG5.setLayout(pnlG5Layout);
        pnlG5Layout.setHorizontalGroup(
            pnlG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG5Layout.setVerticalGroup(
            pnlG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 70, 70));

        pnlF4.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlF4Layout = new javax.swing.GroupLayout(pnlF4);
        pnlF4.setLayout(pnlF4Layout);
        pnlF4Layout.setHorizontalGroup(
            pnlF4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF4Layout.setVerticalGroup(
            pnlF4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 70));

        pnlE3.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlE3Layout = new javax.swing.GroupLayout(pnlE3);
        pnlE3.setLayout(pnlE3Layout);
        pnlE3Layout.setHorizontalGroup(
            pnlE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE3Layout.setVerticalGroup(
            pnlE3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 70, 70));

        pnlD2.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlD2Layout = new javax.swing.GroupLayout(pnlD2);
        pnlD2.setLayout(pnlD2Layout);
        pnlD2Layout.setHorizontalGroup(
            pnlD2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD2Layout.setVerticalGroup(
            pnlD2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 70, 70));

        pnlC1.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlC1Layout = new javax.swing.GroupLayout(pnlC1);
        pnlC1.setLayout(pnlC1Layout);
        pnlC1Layout.setHorizontalGroup(
            pnlC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlC1Layout.setVerticalGroup(
            pnlC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 70, 70));

        pnlA1.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlA1Layout = new javax.swing.GroupLayout(pnlA1);
        pnlA1.setLayout(pnlA1Layout);
        pnlA1Layout.setHorizontalGroup(
            pnlA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA1Layout.setVerticalGroup(
            pnlA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 70, 70));

        pnlD1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlD1Layout = new javax.swing.GroupLayout(pnlD1);
        pnlD1.setLayout(pnlD1Layout);
        pnlD1Layout.setHorizontalGroup(
            pnlD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlD1Layout.setVerticalGroup(
            pnlD1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 70, 70));

        pnlE2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlE2Layout = new javax.swing.GroupLayout(pnlE2);
        pnlE2.setLayout(pnlE2Layout);
        pnlE2Layout.setHorizontalGroup(
            pnlE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE2Layout.setVerticalGroup(
            pnlE2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 70));

        pnlF3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlF3Layout = new javax.swing.GroupLayout(pnlF3);
        pnlF3.setLayout(pnlF3Layout);
        pnlF3Layout.setHorizontalGroup(
            pnlF3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF3Layout.setVerticalGroup(
            pnlF3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 70, 70));

        pnlG4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlG4Layout = new javax.swing.GroupLayout(pnlG4);
        pnlG4.setLayout(pnlG4Layout);
        pnlG4Layout.setHorizontalGroup(
            pnlG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG4Layout.setVerticalGroup(
            pnlG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, 70));

        pnlH5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlH5Layout = new javax.swing.GroupLayout(pnlH5);
        pnlH5.setLayout(pnlH5Layout);
        pnlH5Layout.setHorizontalGroup(
            pnlH5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH5Layout.setVerticalGroup(
            pnlH5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 70, 70));

        pnlA36.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlA36Layout = new javax.swing.GroupLayout(pnlA36);
        pnlA36.setLayout(pnlA36Layout);
        pnlA36Layout.setHorizontalGroup(
            pnlA36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlA36Layout.setVerticalGroup(
            pnlA36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlA36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 70, 70));

        pnlH1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlH1Layout = new javax.swing.GroupLayout(pnlH1);
        pnlH1.setLayout(pnlH1Layout);
        pnlH1Layout.setHorizontalGroup(
            pnlH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH1Layout.setVerticalGroup(
            pnlH1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        pnlH2.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlH2Layout = new javax.swing.GroupLayout(pnlH2);
        pnlH2.setLayout(pnlH2Layout);
        pnlH2Layout.setHorizontalGroup(
            pnlH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH2Layout.setVerticalGroup(
            pnlH2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 70, 70));

        pnlH4.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlH4Layout = new javax.swing.GroupLayout(pnlH4);
        pnlH4.setLayout(pnlH4Layout);
        pnlH4Layout.setHorizontalGroup(
            pnlH4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH4Layout.setVerticalGroup(
            pnlH4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, 70));

        pnlG3.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlG3Layout = new javax.swing.GroupLayout(pnlG3);
        pnlG3.setLayout(pnlG3Layout);
        pnlG3Layout.setHorizontalGroup(
            pnlG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG3Layout.setVerticalGroup(
            pnlG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 70, 70));

        pnlF2.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlF2Layout = new javax.swing.GroupLayout(pnlF2);
        pnlF2.setLayout(pnlF2Layout);
        pnlF2Layout.setHorizontalGroup(
            pnlF2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF2Layout.setVerticalGroup(
            pnlF2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 70, 70));

        pnlE1.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlE1Layout = new javax.swing.GroupLayout(pnlE1);
        pnlE1.setLayout(pnlE1Layout);
        pnlE1Layout.setHorizontalGroup(
            pnlE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlE1Layout.setVerticalGroup(
            pnlE1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 70, 70));

        pnlG1.setBackground(new java.awt.Color(126, 162, 214));

        javax.swing.GroupLayout pnlG1Layout = new javax.swing.GroupLayout(pnlG1);
        pnlG1.setLayout(pnlG1Layout);
        pnlG1Layout.setHorizontalGroup(
            pnlG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG1Layout.setVerticalGroup(
            pnlG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));

        pnlG2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlG2Layout = new javax.swing.GroupLayout(pnlG2);
        pnlG2.setLayout(pnlG2Layout);
        pnlG2Layout.setHorizontalGroup(
            pnlG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlG2Layout.setVerticalGroup(
            pnlG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 70));

        pnlH3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlH3Layout = new javax.swing.GroupLayout(pnlH3);
        pnlH3.setLayout(pnlH3Layout);
        pnlH3Layout.setHorizontalGroup(
            pnlH3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlH3Layout.setVerticalGroup(
            pnlH3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 70, 70));

        pnlF1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlF1Layout = new javax.swing.GroupLayout(pnlF1);
        pnlF1.setLayout(pnlF1Layout);
        pnlF1Layout.setHorizontalGroup(
            pnlF1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        pnlF1Layout.setVerticalGroup(
            pnlF1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnlFondoTablero.add(pnlF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 70));

        pnlBordeIzquierdo.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeIzquierdoLayout = new javax.swing.GroupLayout(pnlBordeIzquierdo);
        pnlBordeIzquierdo.setLayout(pnlBordeIzquierdoLayout);
        pnlBordeIzquierdoLayout.setHorizontalGroup(
            pnlBordeIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlBordeIzquierdoLayout.setVerticalGroup(
            pnlBordeIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlBordeSuperior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeSuperiorLayout = new javax.swing.GroupLayout(pnlBordeSuperior);
        pnlBordeSuperior.setLayout(pnlBordeSuperiorLayout);
        pnlBordeSuperiorLayout.setHorizontalGroup(
            pnlBordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlBordeSuperiorLayout.setVerticalGroup(
            pnlBordeSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        pnlBordeDerecho.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeDerechoLayout = new javax.swing.GroupLayout(pnlBordeDerecho);
        pnlBordeDerecho.setLayout(pnlBordeDerechoLayout);
        pnlBordeDerechoLayout.setHorizontalGroup(
            pnlBordeDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pnlBordeDerechoLayout.setVerticalGroup(
            pnlBordeDerechoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        pnlBordeInferior.setBackground(new java.awt.Color(0, 109, 200));

        javax.swing.GroupLayout pnlBordeInferiorLayout = new javax.swing.GroupLayout(pnlBordeInferior);
        pnlBordeInferior.setLayout(pnlBordeInferiorLayout);
        pnlBordeInferiorLayout.setHorizontalGroup(
            pnlBordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        pnlBordeInferiorLayout.setVerticalGroup(
            pnlBordeInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlBordeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBordeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlBordeDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pnlBordeIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBordeSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(pnlBordeInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBordeDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlFondoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlBordeIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlA1;
    private javax.swing.JPanel pnlA2;
    private javax.swing.JPanel pnlA3;
    private javax.swing.JPanel pnlA36;
    private javax.swing.JPanel pnlA4;
    private javax.swing.JPanel pnlA5;
    private javax.swing.JPanel pnlA6;
    private javax.swing.JPanel pnlA7;
    private javax.swing.JPanel pnlA8;
    private javax.swing.JPanel pnlB1;
    private javax.swing.JPanel pnlB2;
    private javax.swing.JPanel pnlB3;
    private javax.swing.JPanel pnlB4;
    private javax.swing.JPanel pnlB5;
    private javax.swing.JPanel pnlB6;
    private javax.swing.JPanel pnlB7;
    private javax.swing.JPanel pnlB8;
    private javax.swing.JPanel pnlBordeDerecho;
    private javax.swing.JPanel pnlBordeInferior;
    private javax.swing.JPanel pnlBordeIzquierdo;
    private javax.swing.JPanel pnlBordeSuperior;
    private javax.swing.JPanel pnlC1;
    private javax.swing.JPanel pnlC2;
    private javax.swing.JPanel pnlC3;
    private javax.swing.JPanel pnlC4;
    private javax.swing.JPanel pnlC5;
    private javax.swing.JPanel pnlC6;
    private javax.swing.JPanel pnlC7;
    private javax.swing.JPanel pnlC8;
    private javax.swing.JPanel pnlD1;
    private javax.swing.JPanel pnlD2;
    private javax.swing.JPanel pnlD3;
    private javax.swing.JPanel pnlD4;
    private javax.swing.JPanel pnlD5;
    private javax.swing.JPanel pnlD6;
    private javax.swing.JPanel pnlD7;
    private javax.swing.JPanel pnlD8;
    private javax.swing.JPanel pnlE1;
    private javax.swing.JPanel pnlE2;
    private javax.swing.JPanel pnlE3;
    private javax.swing.JPanel pnlE4;
    private javax.swing.JPanel pnlE5;
    private javax.swing.JPanel pnlE6;
    private javax.swing.JPanel pnlE7;
    private javax.swing.JPanel pnlE8;
    private javax.swing.JPanel pnlF1;
    private javax.swing.JPanel pnlF2;
    private javax.swing.JPanel pnlF3;
    private javax.swing.JPanel pnlF4;
    private javax.swing.JPanel pnlF5;
    private javax.swing.JPanel pnlF6;
    private javax.swing.JPanel pnlF7;
    private javax.swing.JPanel pnlF8;
    private javax.swing.JPanel pnlFondoTablero;
    private javax.swing.JPanel pnlG1;
    private javax.swing.JPanel pnlG2;
    private javax.swing.JPanel pnlG3;
    private javax.swing.JPanel pnlG4;
    private javax.swing.JPanel pnlG5;
    private javax.swing.JPanel pnlG6;
    private javax.swing.JPanel pnlG7;
    private javax.swing.JPanel pnlG8;
    private javax.swing.JPanel pnlH1;
    private javax.swing.JPanel pnlH2;
    private javax.swing.JPanel pnlH3;
    private javax.swing.JPanel pnlH4;
    private javax.swing.JPanel pnlH5;
    private javax.swing.JPanel pnlH6;
    private javax.swing.JPanel pnlH7;
    private javax.swing.JPanel pnlH8;
    // End of variables declaration//GEN-END:variables
}
